# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-27 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_courserecord_scorerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerecord',
            name='score',
            field=models.IntegerField(help_text='违纪扣分写负值，表现优异加分写正值', verbose_name='分值'),
        ),
    ]
