# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181217_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '离线')], verbose_name='状态')),
            ],
        ),
    ]
