# Generated by Django 2.0.1 on 2018-07-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='book',
            name='read_num',
        ),
    ]
