# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-02 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20190501_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=32, verbose_name='图标'),
        ),
    ]
