# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-18 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, verbose_name='角色'),
        ),
    ]
