# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190531_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='emali',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='邮箱'),
        ),
    ]
