# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=50, unique=True, verbose_name='资产编号')),
                ('asset_type', models.IntegerField(choices=[(1, '笔记本'), (2, '台式机'), (3, '显示器')], default=1, verbose_name='设备类型')),
                ('company', models.IntegerField(choices=[(1, '客佳信息'), (2, '达欧百希特'), (3, '其他')], default=1, verbose_name='所属公司')),
                ('status', models.IntegerField(choices=[(1, '使用中'), (2, '未使用'), (3, '故障'), (4, '其他')], default=1, verbose_name='设备状态')),
                ('vendor', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备厂商')),
                ('price', models.IntegerField(blank=True, verbose_name='价格')),
                ('buy_time', models.DateField(blank=True, max_length=50, verbose_name='购买时间')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU型号')),
                ('cpu_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU数量')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='内存大小')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='硬盘信息')),
                ('sn', models.CharField(blank=True, max_length=60, null=True, verbose_name='SN号码')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
            ],
        ),
    ]
