# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='cpu_num',
        ),
        migrations.AlterField(
            model_name='computer',
            name='disk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='磁盘'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='内存'),
        ),
    ]
