# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-31 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190531_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='租赁人')),
                ('rental_time', models.DateField(auto_now_add=True, verbose_name='借出/归还时间')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='buy_time',
            field=models.DateField(blank=True, verbose_name='购买时间'),
        ),
        migrations.AddField(
            model_name='rentalrecord',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Computer', verbose_name='资产编号'),
        ),
    ]
