# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190531_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrecord',
            name='rental_status',
            field=models.IntegerField(choices=[(1, '租赁'), (2, '归还')], default=1, verbose_name='状态'),
        ),
    ]
