# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-31 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20190531_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.IntegerField(choices=[(1, '2GB'), (2, '4GB'), (3, '8GB'), (4, '16GB'), (5, '32GB')], default=3, verbose_name='内存'),
        ),
    ]
