# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20190531_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
