# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_fixphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='buy_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SN号码'),
        ),
    ]
