# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-04 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190531_1646'),
        ('assets', '0009_auto_20190602_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixphone',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='fixphone',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='fixphone',
            name='user',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='使用者'),
        ),
    ]
