# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20190604_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixphone',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
