# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_department_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalMachineManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, verbose_name='主机名称')),
                ('intranet', models.GenericIPAddressField(db_index=True, verbose_name='内网IP')),
                ('external', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('specification', models.CharField(blank=True, default='4C8G', max_length=32, null=True, verbose_name='规格')),
                ('system', models.CharField(max_length=32, verbose_name='操作系统')),
                ('status', models.IntegerField(choices=[(1, '使用中'), (2, '待删除')], default=1, verbose_name='状态')),
                ('principal', models.CharField(max_length=32, verbose_name='负责人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
    ]
