# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_localmachinemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='服务名称')),
                ('deployport', models.IntegerField(max_length=16, verbose_name='部署端口')),
                ('env', models.IntegerField(choices=[(1, '生产环境'), (2, '准生产环境'), (3, '测试环境'), (4, '开发环境')], verbose_name='部署环境')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='FixPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.IntegerField(max_length=16, verbose_name='分机号')),
                ('straight_line', models.IntegerField(blank=True, max_length=32, null=True, verbose_name='直线号码')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.EmployeeDepartment', verbose_name='所属部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Employee', verbose_name='使用者')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, verbose_name='主机名称')),
                ('intranet', models.GenericIPAddressField(db_index=True, verbose_name='内网IP')),
                ('external', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('specification', models.CharField(blank=True, default='4C8G', max_length=32, null=True, verbose_name='规格')),
                ('system', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作系统')),
                ('status', models.IntegerField(choices=[(1, '使用中'), (2, '待删除')], default=1, verbose_name='状态')),
                ('principal', models.CharField(max_length=32, verbose_name='负责人')),
                ('supplier', models.IntegerField(choices=[(1, '本地机房'), (2, '阿里云')], default=1, verbose_name='供应商')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=32, verbose_name='资产编码')),
                ('status', models.IntegerField(choices=[(1, '闲置'), (2, '使用中'), (3, '报废')], default=1, verbose_name='状态')),
                ('types', models.IntegerField(choices=[(1, '笔记本'), (2, '台式机'), (3, '显示器'), (4, '鼠标'), (5, 'IPAD'), (6, '服务器'), (7, '投影仪'), (7, '手机')], default=1, verbose_name='设备类型')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='序列号')),
                ('buydate', models.DateField(auto_now_add=True, max_length=128, verbose_name='购买日期')),
                ('warrantydate', models.DateField(blank=True, null=True, verbose_name='保修日期')),
                ('cpu', models.CharField(blank=True, max_length=32, null=True, verbose_name='cpu')),
                ('mem', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('system', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.EmployeeDepartment', verbose_name='部门')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Employee', verbose_name='使用者')),
            ],
        ),
        migrations.DeleteModel(
            name='LocalMachineManagement',
        ),
        migrations.AddField(
            model_name='employee',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.EmployeeDepartment', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='deployservice',
            name='deployip',
            field=models.ManyToManyField(to='asset.Machine', verbose_name='部署地址'),
        ),
    ]
