# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20190301_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployservice',
            name='deployport',
            field=models.IntegerField(verbose_name='部署端口'),
        ),
        migrations.AlterField(
            model_name='fixphone',
            name='extension',
            field=models.IntegerField(verbose_name='分机号'),
        ),
        migrations.AlterField(
            model_name='fixphone',
            name='straight_line',
            field=models.IntegerField(blank=True, null=True, verbose_name='直线号码'),
        ),
    ]
