# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20190301_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixphone',
            name='straight_line',
            field=models.IntegerField(blank=True, default=38959191, null=True, verbose_name='直线号码'),
        ),
    ]
