# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20190301_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='principal',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='负责人'),
        ),
    ]
