# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20190301_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixphone',
            name='user',
            field=models.CharField(max_length=32, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.EmployeeDepartment', verbose_name='使用部门'),
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='status',
            field=models.IntegerField(choices=[(1, '闲置'), (2, '使用中'), (3, '报废')], default=1, verbose_name='设备状态'),
        ),
    ]
