# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20190302_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixphone',
            name='depart',
            field=models.CharField(max_length=32, verbose_name='所属部门'),
        ),
    ]
