# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20190302_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixphone',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.EmployeeDepartment', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='fixphone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Employee', verbose_name='使用者'),
        ),
    ]
