# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20190302_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixphone',
            name='depart',
            field=models.CharField(max_length=32, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='fixphone',
            name='user',
            field=models.CharField(max_length=32, verbose_name='使用者'),
        ),
    ]
