# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-04 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20190302_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depart',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='部门'),
        ),
    ]
